on:
  push:
    tags: 
      - "v*"
name: Publish Module to PowerShell Gallery
jobs:
  publish-module:
    name: Publish PowerShell Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pcgeek86/publish-powershell-module-action@v20
        with:
          # The NuGet API Key for PowerShell Gallery, with permission to push this module.
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
